# Generated by Django 5.2.7 on 2025-10-08 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networknode", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="networknode",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Звено сети",
                "verbose_name_plural": "Звенья сети",
            },
        ),
        migrations.AlterField(
            model_name="networknode",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependent_nodes",
                to="networknode.networknode",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="network_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="networknode.networknode",
                verbose_name="Звено сети",
            ),
        ),
    ]
